version: '3.9'
services:
  db:
    image: mariadb:10.5.12
    restart: always
    environment:
      MYSQL_DATABASE: 'raph_bot_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: